baseURL = 'https://paramanuseniorshealth.org/'
canonifyURLs = true
title = ""                                     # Leave this empty to not have the title overlay the menu
author = "Dr. Venu Babu Pentyala"
copyright = "Launched On 7th March 2022"

timeZone = 'Asia/Kolkata'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"

disableHugoGeneratorInject = true
enableRobotsTXT = true
# enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
googleAnalytics = "G-BGSPDZEPPY"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[[frontmatter.defaults]]
[frontmatter.defaults.where]
kind = "page"
[frontmatter.defaults.values]
layout = "single"
type = "page"
draft = false
weight = 20
[frontmatter.defaults.values.menu.main]
parent = "General Information"

[taxonomies]
tag = "tags"
category = "categories"
series = 'series'
# author = "authors"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
#  post = "/post/:title/"

[params]
themeVariant = "blue"
