backend:
  name: github
  repo: revanthp/parmanuseniorhealth.github.io
  branch: main
  base_url: https://decap.paramanuseniorshealth.org
  site_domain: paramanuseniorshealth.org
  auth_type: implicit
  auth_endpoint: auth
  squash_merges: true

media_folder: "static/files"
public_folder: "public"
publish_mode: editorial_workflow
logo_url: https://paramanuseniorshealth.org/images/logo.jpeg
search: false
show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# ─── DRY: anchors for reuse ───────────────────────────────────────────
collection_defaults: &collection_defaults
  create: true
  delete: false
  slug: "{{year}}-{{slug}}"
  identifier_field: title

title: &title { name: "title", label: "Title" }
date: &date { name: "date", label: "Publish Date", widget: "hidden", default: "{{now}}" }
lastmod: &lastmod { name: "lastmod", label: "Last Modified", widget: "hidden", default: "{{now}}" }
type: &type { name: "type", label: "Type", widget: "hidden", default: "page" }
weight: &weight { name: "weight", label: "Weight", widget: "hidden", default: 20 }
layout: &layout { name: "layout", label: "Layout", widget: "hidden", default: "single" }
desc: &desc { name: "description", label: "Description", widget: "text", required: false }
tags: &tags { name: "tags", label: "Tags", widget: "list", required: false }
body: &body { name: "body", label: "Body", widget: "markdown" }
upload:
    &upload {
      name: "upload",
      label: "Attachments",
      widget: "file",
      multiple: true,
      folder: "/static/files/",
      required: false,
    }

# ─── Collections ────────────────────────────────────────────────────
collections:
  # — Single-file “About” page —
  - name: "pages"
    label: "Pages"
    files:
      - <<: *collection_defaults
        file: "content/about.md"
        name: "about"
        label: "About Page"
        preview_path: "/about"
        fields:
          - *title
          - *date
          - *lastmod
          - *weight
          - *type
          - *layout
          - *desc
          - *tags
          - *body
          - *upload

  # — General Services —
  - <<: *collection_defaults
    name: "general-services"
    label: "General Services"
    folder: "content/general-services"
    preview_path: "/general-services/{{slug}}"
    fields:
      - *title
      - *date
      - *lastmod
      - *weight
      - *type
      - *layout
      - *desc
      - *tags
      - *body
      - *upload
      - label: "Menu"
        name: "menu"
        widget: "hidden"
        collapsed: true
        fields: [{ name: "main.parent", widget: "hidden", default: "General Services" }]

  # — Health Matters —
  - <<: *collection_defaults
    name: "health-matters"
    label: "Health Matters"
    folder: "content/health-matters"
    preview_path: "/health-matters/{{slug}}"
    fields:
      - *title
      - *date
      - *lastmod
      - *weight
      - *type
      - *layout
      - *desc
      - *tags
      - *body
      - *upload
      - label: "Menu"
        name: "menu"
        widget: "hidden"
        collapsed: true
        fields: [{ name: "main.parent", widget: "hidden", default: "Health Matters" }]

  # — Pension —
  - <<: *collection_defaults
    name: "pension"
    label: "Pension"
    folder: "content/pension"
    preview_path: "/pension/{{slug}}"
    fields:
      - *title
      - *date
      - *lastmod
      - *weight
      - *type
      - *layout
      - *desc
      - *tags
      - *body
      - *upload
      - label: "Menu"
        name: "menu"
        widget: "hidden"
        collapsed: true
        fields: [{ name: "main.parent", widget: "hidden", default: "Pension" }]

  # — Tel Numbers —
  - <<: *collection_defaults
    name: "tel-numbers"
    label: "Tel Numbers"
    folder: "content/tel-numbers"
    preview_path: "/tel-numbers/{{slug}}"
    fields:
      - *title
      - *date
      - *lastmod
      - *weight
      - *type
      - *layout
      - *desc
      - *tags
      - *body
      - *upload
      - label: "Menu"
        name: "menu"
        widget: "hidden"
        collapsed: true
        fields: [{ name: "main.parent", widget: "hidden", default: "Tel Numbers" }]
