# local_backend: true
# url: http://localhost:8081/api/v1
# when accessing the local site from a host other than 'localhost' or '127.0.0.1'
# allowed_hosts: ["192.168.0.1"]
backend:
  name: github
  repo: revanthp/parmanuseniorhealth.github.io
  branch: main
  base_url: https://paramanuseniorshealth.org
  auth_type: implicit
media_folder: "static"
public_folder: "public"

collections:
  - name: "general-services"
    label: "General-Services"
    folder: "content/general-services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "health-matters"
    label: "Health-Matters"
    folder: "content/health-matters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "pension"
    label: "pension"
    folder: "content/pension"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "tel-numbers"
    label: "Tel-Numbers"
    folder: "content/tel-numbers"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
